---
version: 2
updates:
  - package-ecosystem: "pip"
    versioning-strategy: "increase"
    directories:
      - "/"
    groups:
      all-django-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
    target-branch: "main"
    reviewers:
      - "chnm/systems"
  - package-ecosystem: "npm"
    directories:
      - "/"
    groups:
      all-npm-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
    target-branch: "main"
    reviewers:
      - "chnm/systems"
