version: '3.9'

services:
  app:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    command: >
        sh -c "poetry run python3 manage.py wait_for_db &&
               poetry run python3 manage.py migrate &&
               poetry run python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: .env

volumes:
  pg-data:
  dj-data:
