version: '3.9'

services:
  app:
    build:
      context: .
    command: >
        sh -c "poetry run python3 manage.py wait_for_db &&
               poetry run python3 manage.py migrate &&
               poetry run python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DATABASE_URL=postgres://devuser:changeme@db:5432/devdb
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  pg-data:
