[tool.poetry]
name = "winterthur-app"
version = "0.1.0"
description = "Web application for Winterthur"
authors = ["Jason Heppler <jason.heppler@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "winterthur_app"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.7"
django-tailwind = "^3.5.0"
django-htmx = "^1.14.0"
django-extensions = "^3.2.1"
django-environ = "^0.10.0"
humanfriendly = "^10.0"
django-taggit = "^3.1.0"
taggit-selectize = "^2.11.0"
django-multiselectfield = "^0.1.12"
psycopg2 = "^2.9.5"
pillow = "^9.4.0"
django-admin-interface = "^0.24.2"
python-dotenv = "^1.0.0"
pytest = "^7.2.2"
pytest-django = "^4.5.2"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
djhtml = "^3.0.6"
pre-commit = "^3.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
