# Generated by Django 4.1.7 on 2023-03-30 18:47

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footnotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footnote",
            options={
                "ordering": [
                    "source",
                    models.OrderBy(
                        django.db.models.functions.comparison.NullIf(
                            "location", models.Value("")
                        ),
                        nulls_last=True,
                    ),
                ]
            },
        ),
    ]
