# Generated by Django 4.1.7 on 2023-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footnotes", "0002_alter_footnote_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
