# Generated by Django 4.1.7 on 2023-04-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0014_delete_collectionmanager"),
        ("footnotes", "0003_alter_footnote_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="source",
            field=models.ForeignKey(
                help_text="Select a fragment that is associated with this footnote.",
                on_delete=django.db.models.deletion.CASCADE,
                to="denig.fragment",
            ),
        ),
    ]
