# Generated by Django 4.1.7 on 2023-05-04 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footnotes", "0004_alter_footnote_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="footnote",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footnote",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
