# Generated by Django 4.1.7 on 2023-03-30 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0003_fragment_languages_fragment_transcription_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fragment",
            options={"ordering": ["document", "created"]},
        ),
        migrations.RemoveField(
            model_name="fragment",
            name="collection",
        ),
        migrations.AddField(
            model_name="fragment",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to a document for this fragment.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="denig.document",
            ),
        ),
    ]
