# Generated by Django 4.1.7 on 2023-03-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0004_alter_fragment_options_remove_fragment_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="page",
            field=models.IntegerField(
                blank=True, default=0, help_text="Page number of the document."
            ),
        ),
    ]
