# Generated by Django 4.1.7 on 2023-03-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0005_document_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image of the document.",
                upload_to="documents",
            ),
        ),
    ]
