# Generated by Django 4.1.7 on 2023-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0009_alter_document_doctype_delete_textblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fragment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
