# Generated by Django 4.1.7 on 2023-03-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0010_alter_fragment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fragment",
            name="line_number",
            field=models.IntegerField(
                blank=True, help_text="Line number of the fragment.", null=True
            ),
        ),
    ]
