# Generated by Django 4.1.7 on 2023-03-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0012_document_docside_alter_document_doctype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="languages",
        ),
        migrations.AlterField(
            model_name="fragment",
            name="languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the language of this fragment.",
                to="denig.language",
            ),
        ),
    ]
