# Generated by Django 4.1.7 on 2023-04-17 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0013_remove_document_languages_alter_fragment_languages"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CollectionManager",
        ),
    ]
