# Generated by Django 4.1.7 on 2023-06-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0014_delete_collectionmanager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="image",
        ),
        migrations.AddField(
            model_name="document",
            name="item_file",
            field=models.FileField(
                blank=True, help_text="Upload a file.", upload_to="files/"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
