# Generated by Django 4.1.7 on 2023-06-23 14:03

import taggit_selectize.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("denig", "0016_remove_document_page_document_page_range_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
