# Generated by Django 4.1.7 on 2023-10-11 21:14

import import_export.admin
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0017_alter_document_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("composer", models.CharField(blank=True, max_length=255)),
                ("year_composed", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "page_range",
                    models.CharField(
                        blank=True,
                        help_text="Page or page range of the document.",
                        max_length=255,
                        null=True,
                        verbose_name="Page",
                    ),
                ),
                (
                    "sheet_music",
                    models.FileField(
                        blank=True,
                        help_text="Upload a file. Click to open a larger image.",
                        null=True,
                        upload_to="files/",
                        verbose_name="File preview",
                    ),
                ),
                (
                    "audio_recordig_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a file.",
                        null=True,
                        upload_to="files/",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            bases=(import_export.admin.ImportExportMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="item_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a file. Click to open a larger image.",
                null=True,
                upload_to="files/",
                verbose_name="File preview",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes about the item. These are not public.",
                verbose_name="Internal notes",
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about the fragment. These will not be public.",
                verbose_name="Internal notes",
            ),
        ),
    ]
