# Generated by Django 4.1.7 on 2023-10-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0018_musicscore_alter_document_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicscore",
            name="audio_recordig_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a file.",
                null=True,
                upload_to="files/",
                verbose_name="Audio recording",
            ),
        ),
        migrations.AlterField(
            model_name="musicscore",
            name="sheet_music",
            field=models.FileField(
                blank=True,
                help_text="Upload a file (PDF or PNG). Click to open a larger image.",
                null=True,
                upload_to="files/",
                verbose_name="Sheet music",
            ),
        ),
    ]
