# Generated by Django 4.1.7 on 2023-11-09 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0019_alter_musicscore_audio_recordig_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musicscore",
            name="composer",
        ),
        migrations.RemoveField(
            model_name="musicscore",
            name="year_composed",
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "image_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recto", "Recto"),
                            ("verso", "Verso"),
                            ("recto and verso", "Recto and Verso"),
                            ("music score", "Music Score"),
                            ("forensics", "Forensics"),
                        ],
                        default="recto",
                        max_length=255,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="denig.document"
                    ),
                ),
            ],
        ),
    ]
