# Generated by Django 4.1.7 on 2023-11-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0020_remove_musicscore_composer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="images",
            old_name="document",
            new_name="related_document",
        ),
        migrations.RemoveField(
            model_name="document",
            name="item_file",
        ),
        migrations.AddField(
            model_name="document",
            name="item_file",
            field=models.ManyToManyField(
                blank=True, to="denig.images", verbose_name="Image"
            ),
        ),
    ]
