# Generated by Django 4.1.7 on 2023-11-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0021_rename_document_images_related_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
