# Generated by Django 4.1.7 on 2023-11-13 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0022_alter_images_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Images",
            new_name="Image",
        ),
    ]
