# Generated by Django 4.1.7 on 2023-11-13 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0023_rename_images_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="item_file",
        ),
    ]
