# Generated by Django 4.1.7 on 2023-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0024_remove_document_item_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="item_file",
            field=models.ManyToManyField(
                blank=True, to="denig.image", verbose_name="Image"
            ),
        ),
    ]
