# Generated by Django 4.1.7 on 2023-11-13 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0025_document_item_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="item_file",
        ),
        migrations.RemoveField(
            model_name="image",
            name="related_document",
        ),
        migrations.AddField(
            model_name="image",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="denig.document",
            ),
        ),
    ]
