# Generated by Django 4.1.7 on 2023-11-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0026_remove_document_item_file_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="document",
            new_name="related_document",
        ),
        migrations.AddField(
            model_name="document",
            name="item_file",
            field=models.ManyToManyField(
                blank=True, to="denig.image", verbose_name="Image"
            ),
        ),
    ]
