# Generated by Django 4.1.7 on 2023-11-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0027_rename_document_image_related_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="item_file",
        ),
        migrations.AlterField(
            model_name="image",
            name="related_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attached_images",
                to="denig.document",
            ),
        ),
    ]
