# Generated by Django 4.1.7 on 2024-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0028_remove_document_item_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes about the item. These are not public.",
                null=True,
                verbose_name="Internal notes",
            ),
        ),
    ]
