# Generated by Django 4.1.7 on 2024-02-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0029_alter_document_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
