# Generated by Django 4.1.7 on 2024-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0030_alter_document_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
