# Generated by Django 4.2.13 on 2024-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0031_document_document_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
