# Generated by Django 4.2.11 on 2024-06-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0031_document_document_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicscore",
            name="related_document",
            field=models.ForeignKey(
                default=4527,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="music_scores",
                to="denig.document",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="docside",
            field=models.CharField(
                blank=True,
                choices=[
                    ("recto", "Recto"),
                    ("verso", "Verso"),
                    ("verso and recto", "Verso and Recto"),
                ],
                default="recto",
                max_length=255,
                verbose_name="Document side",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("recto", "Recto"),
                    ("verso", "Verso"),
                    ("verso and recto", "Verso and Recto"),
                    ("music score", "Music Score"),
                    ("forensics", "Forensics"),
                ],
                default="recto",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="musicscore",
            name="audio_recordig_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a file.",
                null=True,
                upload_to="media/",
                verbose_name="Audio recording",
            ),
        ),
        migrations.AlterField(
            model_name="musicscore",
            name="sheet_music",
            field=models.FileField(
                blank=True,
                help_text="Upload a file (PDF or PNG).",
                null=True,
                upload_to="media/",
                verbose_name="Sheet music",
            ),
        ),
    ]
