# Generated by Django 4.2.11 on 2024-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0032_musicscore_related_document_alter_document_docside_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicscore",
            name="arrangement_by",
            field=models.CharField(
                blank=True,
                help_text="Name of who arranged the music score.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="musicscore",
            name="composer",
            field=models.CharField(
                blank=True,
                help_text="Composer of the music, if known.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="musicscore",
            name="translated_by",
            field=models.CharField(
                blank=True,
                help_text="Name of who translated the music score.",
                max_length=255,
                null=True,
            ),
        ),
    ]
