# Generated by Django 4.2.11 on 2024-06-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0033_musicscore_arrangement_by_musicscore_composer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musicscore",
            old_name="audio_recordig_file",
            new_name="audio_recording_file",
        ),
        migrations.AlterField(
            model_name="document",
            name="doctype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("music score", "Music Score"),
                    ("illumination", "Illumination"),
                    ("text", "Text"),
                ],
                default="text",
                max_length=255,
                verbose_name="Document type",
            ),
        ),
    ]
