# Generated by Django 4.2.13 on 2024-06-13 14:55

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0035_alter_document_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                populate_from="page_range",
                unique=True,
            ),
        ),
    ]
