# Generated by Django 4.2.13 on 2024-06-13 15:11

import django_extensions.db.fields
from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    doc = apps.get_model("denig", "Document")
    for instance in doc.objects.all():
        print("Generating slug for %s" % instance)
        instance.save()  # Will trigger slug update


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0038_remove_document_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="Document",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                populate_from="page_range",
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
