# Generated by Django 4.2.13 on 2024-07-31 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "denig",
            "0034_rename_audio_recordig_file_musicscore_audio_recording_file_and_more",
        ),
        ("denig", "0040_alter_document_slug"),
    ]

    operations = []
