# Generated by Django 4.2.13 on 2024-09-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0041_merge_20240731_1346"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="caption",
            field=models.TextField(
                blank=True, help_text="Caption for the image.", null=True
            ),
        ),
    ]
