# Generated by Django 4.2.13 on 2024-09-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0042_image_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Captions for the images to provide extra context for the viewer.",
                null=True,
                verbose_name="Image caption",
            ),
        ),
    ]
