# Generated by Django 4.1.7 on 2023-06-23 14:24

import django.db.models.deletion
import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0002_alter_essay_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", prose.fields.DocumentContentField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="essay",
            name="meta_description",
        ),
        migrations.AlterField(
            model_name="essay",
            name="body",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="essays.essaycontent"
            ),
        ),
    ]
