# Generated by Django 4.1.7 on 2023-10-11 19:30

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0003_essaycontent_remove_essay_meta_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essay",
            name="body",
            field=prose.fields.RichTextField(),
        ),
    ]
