# Generated by Django 4.1.7 on 2023-10-11 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prose", "0002_alter_document_id"),
        ("essays", "0005_alter_essay_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essay",
            name="body",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="prose.document"
            ),
        ),
        migrations.DeleteModel(
            name="EssayContent",
        ),
    ]
