# Generated by Django 4.1.7 on 2023-10-11 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("essays", "0006_alter_essay_body_delete_essaycontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="essay",
            name="published",
            field=models.BooleanField(
                default=False, help_text="Publish this essay? If checked, yes."
            ),
        ),
    ]
