# Generated by Django 4.1.7 on 2023-10-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0007_alter_author_user_alter_essay_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="user",
        ),
        migrations.AddField(
            model_name="author",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="How the author's name should be displayed, if different from their full name.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="author",
            name="full_name",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="A short biography of the author. Max characters is 600.",
                max_length=600,
            ),
        ),
    ]
