# Generated by Django 4.1.7 on 2023-10-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0008_remove_author_user_author_display_name_author_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(
                help_text="The author's email address.", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="essay",
            name="slug",
            field=models.SlugField(
                default="", editable=False, max_length=255, unique=True
            ),
        ),
    ]
