# Generated by Django 4.1.7 on 2023-11-09 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0009_alter_author_email_alter_essay_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="institution",
            field=models.TextField(
                blank=True,
                help_text="The author's institutional affiliation.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("credit", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField(blank=True, null=True)),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="essays.essay"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
