# Generated by Django 4.2.11 on 2024-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0012_essaypage_rename_blogindexpage_essayindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="essaypage",
            name="author",
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
