# Generated by Django 4.2.11 on 2024-03-20 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0014_essaypagegalleryimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EssayPageGalleryImage",
        ),
    ]
