# Generated by Django 4.2.11 on 2024-03-20 19:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0016_essaypagegalleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="essaypage",
            name="author_bio",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
