# Generated by Django 4.2.11 on 2024-03-20 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0017_essaypage_author_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="essay",
            name="author",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="body",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="images",
            name="essay",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Essay",
        ),
        migrations.DeleteModel(
            name="Images",
        ),
    ]
