# Generated by Django 4.2.11 on 2024-06-17 15:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("essays", "0018_remove_essay_author_remove_essay_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="essaypage",
            name="doi",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="essaypage",
            name="doi_url",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
