# Generated by Django 4.2.13 on 2024-10-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denig", "0043_alter_image_caption"),
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("essays", "0022_forensicpage_galleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="forensicpage",
            name="related_manuscript_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="denig.document",
            ),
        ),
        migrations.AlterField(
            model_name="forensicpage",
            name="preview_image",
            field=models.ForeignKey(
                blank=True,
                help_text="If no preview image is provided, the first image in the gallery will be used.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
